import { writeFile } from "node:fs/promises";
import path from "node:path";
import { TOPIC_SECTIONS, TOPIC_TAXONOMY } from "./topic-taxonomy.js";

/**
 * The site cannot import from `src/`, so its copy of the vocabulary is
 * generated. `src/topic-taxonomy.ts` stays the single source of truth and
 * `topic-taxonomy.test.ts` fails if the generated file drifts.
 */
export function renderSiteTaxonomy() {
  const sections = TOPIC_SECTIONS.map(
    (section) => `  { slug: "${section.slug}", label: ${JSON.stringify(section.label)}, accent: "${sectionAccent(section.slug)}", artworkSlug: "${section.artworkSlug ?? section.slug}" },`,
  ).join("\n");
  const topics = TOPIC_TAXONOMY.map((topic) => `  {
    slug: "${topic.slug}",
    section: "${topic.section}",
    label: ${JSON.stringify(topic.label)},
    description: ${JSON.stringify(topic.description)},
  },`).join("\n");

  return `// Generated by \`pnpm topics:sync\` from src/topic-taxonomy.ts — do not edit by hand.

export type TopicSection = { slug: string; label: string; accent: string; artworkSlug: string };
export type TopicDefinition = { slug: string; section: string; label: string; description: string };

export const TOPIC_SECTIONS: TopicSection[] = [
${sections}
];

export const TOPIC_TAXONOMY: TopicDefinition[] = [
${topics}
];
`;
}

function sectionAccent(slug: string) {
  const accents: Record<string, string> = {
    reasoning: "blue",
    agents: "orange",
    multimodal: "pink",
    "video-spatial": "red",
    systems: "cyan",
    robotics: "yellow",
    science: "violet",
    safety: "blue",
  };
  return accents[slug] ?? "blue";
}

// Only write when invoked directly, so the test can import renderSiteTaxonomy.
if (process.argv[1]?.endsWith("generate-site-taxonomy.ts")) {
  const outputPath = path.join(process.cwd(), "site", "lib", "topic-taxonomy.ts");
  await writeFile(outputPath, renderSiteTaxonomy());
  process.stdout.write(`Wrote ${TOPIC_TAXONOMY.length} topics to ${path.relative(process.cwd(), outputPath)}\n`);
}
